"""Mensagem de migração

Revision ID: c06096448c52
Revises: 
Create Date: 2025-04-03 10:19:05.508688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c06096448c52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('usuario')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_constraint('eventos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizadores', ['organizador_id'], ['id'])

    with op.batch_alter_table('perfis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))
        batch_op.drop_index('usuario_id')
        batch_op.drop_constraint('perfis_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('github')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('telefone')
        batch_op.drop_column('site')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('nome_completo')
        batch_op.drop_column('twitter')
        batch_op.drop_column('avatar')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('biografia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biografia', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('cidade', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('avatar', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('twitter', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('nome_completo', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('data_nascimento', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('site', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('linkedin', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('github', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('perfis_ibfk_1', 'usuario', ['usuario_id'], ['id'])
        batch_op.create_index('usuario_id', ['usuario_id'], unique=True)
        batch_op.drop_column('foto')
        batch_op.drop_column('bio')

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('eventos_ibfk_1', 'usuarios', ['organizador_id'], ['id'])

    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('celular', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
